export const API_URL = {
    BASE: 'http://localhost:8080',
    USER: {
        BASE: '/user',
        REGISTER: '/register',
        LOGIN: '/login',
        INFO: '/info',
        PASSWORD: '/password',
        ADMIN: '/admin',
        LIST: '/list',
    },
    JWT: {
        BASE: '/jwt',
        REFRESH: '/refresh',
        LOG_OUT: '/logout',
        BLACKLIST_VERIFY: '/blacklist-verify',
        VERIFY: '/verify',
    },
    ROLE: {
        BASE: '/role',
        REGISTER_ROLE_LIST: '/register-list',
    },
    USER_ROLE: {
        BASE: '/user-role',
    },
    CENTER: {
        BASE: '/center',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        USER: '/user',
        DROPDOWN: '/dropdown',
        WORKING_TIME: '/working-time',
        INFO: '/info',
        CLOSED: '/closed',
        STATISTICS: '/statistics',
    },
    COURT: {
        BASE: '/court',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        USER: '/user',
        CENTER: '/center',
        DROPDOWN: '/dropdown',
    },
    PRODUCT: {
        BASE: '/product',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        DROPDOWN: '/dropdown',
    },
    PRODUCT_INVENTORY: {
        BASE: '/product-inventory',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        USER: '/user',
        PRODUCT: '/product',
        CENTER: '/center',
        FILTER: '/filter',
    },
    IMAGE: {
        BASE: '/image',
        PRODUCT: '/product',
        CENTER: '/center',
        INFO: '/info',
        LIST: '/list',
        THUMBNAIL_INFO: '/thumbnail-info',
        SHOWCASE_INFO: '/showcase-info',
    },
    EMPLOYEE_MANAGEMENT: {
        BASE: '/employee-management',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
    },
    COURT_BOOKING: {
        BASE: '/court-booking',
        LIST: '/list',
        USER: '/user',
        CENTER_OWNER: '/center-owner',
        CENTER_LIST: '/center-list',
        CENTER: '/center',
        COURT: '/court',
        FILTER: '/filter',
        DATE: '/date',
        DETAIL: '/detail',
        ID: '/id',
        CANCEL: '/cancel',
        CHECKOUT: '/checkout',
        STATISTICS: '/statistics',
        DAILY: '/daily',
    },
    CENTER_REVIEW: {
        BASE: '/center-review',
        LIST: '/list',
        USER: '/user',
        CENTER_OWNER: '/center-owner',
        FILTER: '/filter',
        CENTER: '/center',
        ADMIN: '/admin',
        APPROVE: '/approve',
        DENIED: '/denied',
    },
    PRODUCT_ORDER: {
        BASE: '/product-order',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        FILTER: '/filter',
        USER: '/user',
        CENTER: '/center',
    },
    BOOKING_ORDER_STATUS: {
        BASE: '/booking-order-status',
        LIST: '/list',
    },
    PRODUCT_ORDER_STATUS: {
        BASE: '/product-order-status',
        LIST: '/list',
    },
    COURT_BOOKING_PRODUCT_ORDER: {
        BASE: '/court-booking-product-order',
        PRODUCT_INVENTORY: '/product-inventory',
        USER: '/user',
        LIST: '/list',
        CENTER_OWNER: '/center-owner',
        COURT_BOOKING: '/court-booking',
        CANCEL: '/cancel',
        CHECKOUT: '/checkout',
    },
};